import type { ItemCosteo, TasasCosteo, CategoriaDef } from '../types/costing';

export const DEFAULT_CATEGORIES: CategoriaDef[] = [
  { id: 'cat-tuberculos', nombre: 'Tubérculos', icono: '🥔' },
  { id: 'cat-hortalizas', nombre: 'Hortalizas', icono: '🍅' },
  { id: 'cat-frutas', nombre: 'Frutas', icono: '🍌' },
  { id: 'cat-alinos', nombre: 'Aliños', icono: '🧄' },
  { id: 'cat-viveres', nombre: 'Víveres', icono: '🛒' },
  { id: 'cat-servicios', nombre: 'Servicios y Fletes', icono: '🚚' },
  { id: 'cat-empaques', nombre: 'Empaques e Insumos', icono: '📦' },
  { id: 'cat-otros', nombre: 'Otros', icono: '🏷️' }
];

export const DEFAULT_EMPAQUES: string[] = [
  'Saco',
  'Cesta',
  'Bulto',
  'Caja',
  'Malla',
  'Kilo Directo',
  'Manojo / Atado',
  'Bandeja',
  'Litro / Garrafa',
  'Servicio / Viaje',
  'Unidad / Pieza'
];

export const CSV_DEFAULT_BASE_PRICES_USDT: Record<string, number> = {
  'Papa': 1.00,
  'Papa Amarilla': 1.00,
  'Tomate': 1.50,
  'Tomate Perita': 1.50,
  'Cebolla': 1.20,
  'Cebolla Cabeza': 1.20,
  'Pimentón': 2.00,
  'Zanahoria': 1.00,
  'Ajo': 4.00,
  'Plátano': 1.50,
  'Plátano Verde / Maduro': 1.50,
  'Limón': 2.50,
  'Limón Criollo / Persa': 2.50,
  'Aguacate': 3.00,
  'Cambur': 1.00,
  'Cambur Guineo': 1.00,
  'Patilla': 0.70,
  'Melón': 1.20,
  'Yuca': 0.90,
  'Yuca Blanca': 0.90,
  'Ocumo / Ñame': 1.10,
  'Calabacín': 1.10,
  'Lechuga': 1.00,
  'Cilantro / Cebollín': 2.00,
  'Batata': 1.00,
  'Naranja': 1.20,
  'Piña': 1.30,
  'Maíz': 1.00,
  'Ají Dulce': 2.50
};

export const INITIAL_TASAS_COSTEO: TasasCosteo = {
  tasaBCV: 76.50,
  tasaParalelo: 95.00,          // Tasa Dólar Paralelo / Monitor / Efectivo
  tasaProveedor: 92.00,         // Tasa Dólar Proveedor / Reposición
  tasaCOP: 3850,
  tasaUSDT: 94.00,              // Tasa Cripto P2P
  tasaCompraCOP_USDT: 3150,     // Factor divisor del CSV (90.000 COP ÷ 3150 = 28.57 USDT)
  factorMargenCOP: 880,         // Factor multiplicador feria
  tasaDivisaBCV: 765,           // Factor divisor divisa feria
  tipoFormula: 'formula_csv_usdt', // Fórmula activa por defecto basada en el CSV
  formulaPersonalizada: {
    variableEntrada: 'costo_origen_empaque',
    monedaResultado: 'VES',
    pasos: [
      { id: 'p-1', nombre: 'Paso 1: Divisor Compra', op: 'div', val: 3150, tipoValor: 'divisor_cop_usdt', activo: true },
      { id: 'p-2', nombre: 'Paso 2: Margen Feria', op: 'mul', val: 880, tipoValor: 'factor_margen', activo: true },
      { id: 'p-3', nombre: 'Paso 3: Divisa Feria', op: 'div', val: 765, tipoValor: 'tasa_divisa_bcv', activo: true }
    ],
    op1: 'div',
    val1: 3150,
    op2: 'mul',
    val2: 880,
    op3: 'div',
    val3: 765
  },
  tipoRedondeoBCV: 'entero',
  preciosBaseUSDT: CSV_DEFAULT_BASE_PRICES_USDT,
  fechaActualizacion: new Date().toISOString()
};

export const INITIAL_COSTING_ITEMS: ItemCosteo[] = [
  // ─── TUBÉRCULOS ───────────────────────────────────────────────
  {
    id: 'cost-1',
    nombre: 'Papa Amarilla / Blanca',
    categoria: 'Tubérculos',
    icono: '🥔',
    tipoEmpaque: 'Saco',
    pesoEmpaqueKg: 45,
    monedaCosto: 'COP',
    costoEmpaque: 90000,
    fleteUnitario: 0.50,
    mermaPorcentaje: 4,
    margenPorcentaje: 30,
    margenMayoristaPorcentaje: 15,
    precioBaseUSDT: 1.00,
    proveedor: 'Camión Mayorista La Grita',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },
  {
    id: 'cost-4',
    nombre: 'Zanahoria',
    categoria: 'Tubérculos',
    icono: '🥕',
    tipoEmpaque: 'Saco',
    pesoEmpaqueKg: 45,
    monedaCosto: 'COP',
    costoEmpaque: 65000,
    fleteUnitario: 0.50,
    mermaPorcentaje: 5,
    margenPorcentaje: 35,
    margenMayoristaPorcentaje: 15,
    precioBaseUSDT: 1.00,
    proveedor: 'Camión Mayorista La Grita',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },
  {
    id: 'cost-13',
    nombre: 'Yuca Blanca',
    categoria: 'Tubérculos',
    icono: '🥔',
    tipoEmpaque: 'Saco',
    pesoEmpaqueKg: 40,
    monedaCosto: 'USD',
    tipoTasaCosto: 'bcv',
    costoEmpaque: 18.00,
    fleteUnitario: 0.40,
    mermaPorcentaje: 5,
    margenPorcentaje: 35,
    margenMayoristaPorcentaje: 15,
    precioBaseUSDT: 0.90,
    proveedor: 'Productores de Barinas',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },
  {
    id: 'cost-14',
    nombre: 'Ocumo / Ñame',
    categoria: 'Tubérculos',
    icono: '🥔',
    tipoEmpaque: 'Saco',
    pesoEmpaqueKg: 30,
    monedaCosto: 'USD',
    tipoTasaCosto: 'proveedor',
    costoEmpaque: 22.00,
    fleteUnitario: 0.40,
    mermaPorcentaje: 5,
    margenPorcentaje: 35,
    margenMayoristaPorcentaje: 15,
    precioBaseUSDT: 1.10,
    proveedor: 'Productores de Monagas',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },
  {
    id: 'cost-18',
    nombre: 'Batata Dulce',
    categoria: 'Tubérculos',
    icono: '🍠',
    tipoEmpaque: 'Saco',
    pesoEmpaqueKg: 35,
    monedaCosto: 'USD',
    tipoTasaCosto: 'paralelo',
    costoEmpaque: 16.00,
    fleteUnitario: 0.40,
    mermaPorcentaje: 4,
    margenPorcentaje: 30,
    margenMayoristaPorcentaje: 15,
    precioBaseUSDT: 1.00,
    proveedor: 'Mercado Mayorista',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },

  // ─── HORTALIZAS ───────────────────────────────────────────────
  {
    id: 'cost-2',
    nombre: 'Tomate Perita',
    categoria: 'Hortalizas',
    icono: '🍅',
    tipoEmpaque: 'Cesta',
    pesoEmpaqueKg: 22,
    monedaCosto: 'COP',
    costoEmpaque: 48000,
    fleteUnitario: 0.40,
    mermaPorcentaje: 6,
    margenPorcentaje: 35,
    margenMayoristaPorcentaje: 18,
    precioBaseUSDT: 1.50,
    proveedor: 'Distribuidora Cúcuta',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },
  {
    id: 'cost-3',
    nombre: 'Cebolla Cabeza',
    categoria: 'Hortalizas',
    icono: '🧅',
    tipoEmpaque: 'Saco',
    pesoEmpaqueKg: 20,
    monedaCosto: 'USD',
    tipoTasaCosto: 'paralelo',
    costoEmpaque: 13.00,
    fleteUnitario: 0.30,
    mermaPorcentaje: 3,
    margenPorcentaje: 30,
    margenMayoristaPorcentaje: 15,
    precioBaseUSDT: 1.20,
    proveedor: 'Mercado Mayorista Táchira',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },
  {
    id: 'cost-5',
    nombre: 'Pimentón Rojo / Verde',
    categoria: 'Hortalizas',
    icono: '🫑',
    tipoEmpaque: 'Cesta',
    pesoEmpaqueKg: 18,
    monedaCosto: 'COP',
    costoEmpaque: 55000,
    fleteUnitario: 0.40,
    mermaPorcentaje: 5,
    margenPorcentaje: 35,
    margenMayoristaPorcentaje: 18,
    precioBaseUSDT: 2.00,
    proveedor: 'Distribuidora Cúcuta',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },
  {
    id: 'cost-15',
    nombre: 'Calabacín',
    categoria: 'Hortalizas',
    icono: '🥒',
    tipoEmpaque: 'Cesta',
    pesoEmpaqueKg: 20,
    monedaCosto: 'VES',
    costoEmpaque: 900,
    fleteUnitario: 0.30,
    mermaPorcentaje: 4,
    margenPorcentaje: 35,
    margenMayoristaPorcentaje: 15,
    precioBaseUSDT: 1.10,
    proveedor: 'Productores Locales en Bolívares',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },
  {
    id: 'cost-16',
    nombre: 'Lechuga Romana / Americana',
    categoria: 'Hortalizas',
    icono: '🥬',
    tipoEmpaque: 'Cesta',
    pesoEmpaqueKg: 12,
    monedaCosto: 'USD',
    tipoTasaCosto: 'bcv',
    costoEmpaque: 10.00,
    fleteUnitario: 0.30,
    mermaPorcentaje: 8,
    margenPorcentaje: 40,
    margenMayoristaPorcentaje: 20,
    precioBaseUSDT: 1.00,
    proveedor: 'Productores de Galipán',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },
  {
    id: 'cost-21',
    nombre: 'Maíz / Jojoto',
    categoria: 'Hortalizas',
    icono: '🌽',
    tipoEmpaque: 'Saco',
    pesoEmpaqueKg: 30,
    monedaCosto: 'VES',
    costoEmpaque: 1200,
    fleteUnitario: 0.40,
    mermaPorcentaje: 5,
    margenPorcentaje: 30,
    margenMayoristaPorcentaje: 15,
    precioBaseUSDT: 1.00,
    proveedor: 'Productores de Guárico',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },

  // ─── FRUTAS ───────────────────────────────────────────────────
  {
    id: 'cost-6',
    nombre: 'Plátano Verde / Maduro',
    categoria: 'Frutas',
    icono: '🍌',
    tipoEmpaque: 'Cesta',
    pesoEmpaqueKg: 25,
    monedaCosto: 'USD',
    tipoTasaCosto: 'proveedor',
    costoEmpaque: 14.00,
    fleteUnitario: 0.50,
    mermaPorcentaje: 4,
    margenPorcentaje: 30,
    margenMayoristaPorcentaje: 15,
    precioBaseUSDT: 1.50,
    proveedor: 'Sur del Lago',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },
  {
    id: 'cost-7',
    nombre: 'Limón Criollo / Persa',
    categoria: 'Frutas',
    icono: '🍋',
    tipoEmpaque: 'Saco',
    pesoEmpaqueKg: 30,
    monedaCosto: 'COP',
    costoEmpaque: 70000,
    fleteUnitario: 0.40,
    mermaPorcentaje: 5,
    margenPorcentaje: 30,
    margenMayoristaPorcentaje: 15,
    precioBaseUSDT: 2.50,
    proveedor: 'Distribuidora Cúcuta',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },
  {
    id: 'cost-8',
    nombre: 'Aguacate Injerto',
    categoria: 'Frutas',
    icono: '🥑',
    tipoEmpaque: 'Cesta',
    pesoEmpaqueKg: 20,
    monedaCosto: 'COP',
    costoEmpaque: 80000,
    fleteUnitario: 0.50,
    mermaPorcentaje: 6,
    margenPorcentaje: 35,
    margenMayoristaPorcentaje: 18,
    precioBaseUSDT: 3.00,
    proveedor: 'Distribuidora Cúcuta',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },
  {
    id: 'cost-10',
    nombre: 'Cambur Guineo / Titiaro',
    categoria: 'Frutas',
    icono: '🍌',
    tipoEmpaque: 'Cesta',
    pesoEmpaqueKg: 20,
    monedaCosto: 'USD',
    tipoTasaCosto: 'bcv',
    costoEmpaque: 8.00,
    fleteUnitario: 0.30,
    mermaPorcentaje: 5,
    margenPorcentaje: 30,
    margenMayoristaPorcentaje: 15,
    precioBaseUSDT: 1.00,
    proveedor: 'Productores de Aragua',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },
  {
    id: 'cost-11',
    nombre: 'Patilla',
    categoria: 'Frutas',
    icono: '🍉',
    tipoEmpaque: 'Bulto',
    pesoEmpaqueKg: 30,
    monedaCosto: 'VES',
    costoEmpaque: 900,
    fleteUnitario: 0.50,
    mermaPorcentaje: 3,
    margenPorcentaje: 35,
    margenMayoristaPorcentaje: 15,
    precioBaseUSDT: 0.70,
    proveedor: 'Productores de Cojedes',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },
  {
    id: 'cost-12',
    nombre: 'Melón Cantaloupe',
    categoria: 'Frutas',
    icono: '🍈',
    tipoEmpaque: 'Cesta',
    pesoEmpaqueKg: 20,
    monedaCosto: 'USD',
    tipoTasaCosto: 'paralelo',
    costoEmpaque: 15.00,
    fleteUnitario: 0.40,
    mermaPorcentaje: 4,
    margenPorcentaje: 35,
    margenMayoristaPorcentaje: 15,
    precioBaseUSDT: 1.20,
    proveedor: 'Productores de Lara',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },
  {
    id: 'cost-19',
    nombre: 'Naranja California / Valencia',
    categoria: 'Frutas',
    icono: '🍊',
    tipoEmpaque: 'Saco',
    pesoEmpaqueKg: 30,
    monedaCosto: 'USD',
    tipoTasaCosto: 'bcv',
    costoEmpaque: 15.00,
    fleteUnitario: 0.40,
    mermaPorcentaje: 5,
    margenPorcentaje: 30,
    margenMayoristaPorcentaje: 15,
    precioBaseUSDT: 1.20,
    proveedor: 'Productores de Carabobo',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },
  {
    id: 'cost-20',
    nombre: 'Piña Miel',
    categoria: 'Frutas',
    icono: '🍍',
    tipoEmpaque: 'Cesta',
    pesoEmpaqueKg: 20,
    monedaCosto: 'USD',
    tipoTasaCosto: 'proveedor',
    costoEmpaque: 14.00,
    fleteUnitario: 0.40,
    mermaPorcentaje: 5,
    margenPorcentaje: 35,
    margenMayoristaPorcentaje: 15,
    precioBaseUSDT: 1.30,
    proveedor: 'Productores de Lara',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },

  // ─── ALIÑOS ───────────────────────────────────────────────────
  {
    id: 'cost-9',
    nombre: 'Ajo Morado / Blanco',
    categoria: 'Aliños',
    icono: '🧄',
    tipoEmpaque: 'Caja',
    pesoEmpaqueKg: 10,
    monedaCosto: 'USD',
    tipoTasaCosto: 'paralelo',
    costoEmpaque: 25.00,
    fleteUnitario: 0.30,
    mermaPorcentaje: 2,
    margenPorcentaje: 35,
    margenMayoristaPorcentaje: 15,
    precioBaseUSDT: 4.00,
    proveedor: 'Importado / Mérida',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },
  {
    id: 'cost-17',
    nombre: 'Cilantro / Cebollín',
    categoria: 'Aliños',
    icono: '🧄',
    tipoEmpaque: 'Cesta',
    pesoEmpaqueKg: 10,
    monedaCosto: 'VES',
    costoEmpaque: 1100,
    fleteUnitario: 0.30,
    mermaPorcentaje: 6,
    margenPorcentaje: 35,
    margenMayoristaPorcentaje: 15,
    precioBaseUSDT: 2.00,
    proveedor: 'Productores de Miranda',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  },
  {
    id: 'cost-22',
    nombre: 'Ají Dulce Llanero',
    categoria: 'Aliños',
    icono: '🫑',
    tipoEmpaque: 'Cesta',
    pesoEmpaqueKg: 12,
    monedaCosto: 'USD',
    tipoTasaCosto: 'bcv',
    costoEmpaque: 18.00,
    fleteUnitario: 0.30,
    mermaPorcentaje: 4,
    margenPorcentaje: 35,
    margenMayoristaPorcentaje: 15,
    precioBaseUSDT: 2.50,
    proveedor: 'Productores de Guárico',
    fechaActualizacion: new Date().toLocaleDateString('es-VE')
  }
];
